name: Run tests

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # install python
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    # checkout the PR
    - uses: actions/checkout@v2
    # cache the pip step for speed
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
    # install the dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # get counts of issues in PR
    - name: Get pylint counts in PR
      run: |
        python pylint_counts.py dummy > now.json
    # checkout default branch
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.repository.default_branch }}
    # get counts of issues in default branch
    - name: Get pylint counts in default branch
      run: |
        python pylint_counts.py dummy > then.json
    # build the report
    - name: Build report
      run: |
        python build_report.py then.json now.json > report.md
        REPORT="${cat report.md}"
        echo "::set-output name=report::$REPORT"
    # make the comment
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        message: |
          Using ${{ github.sha }}:
          ```
          ${{ steps.lint.outputs.report }}
          ```
