name: Run tests

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # install python
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    # checkout the PR
    - uses: actions/checkout@v2
    # checkout the default branch
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.repository.default_branch }}
        path: _default_branch
    # cache the pip step for speed
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
    # install the dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # get counts of issues
    # build the report
    - name: Build report
      id: report
      run: |
        python pylint_counts.py * > now.json
        python pylint_counts.py _default_branch/* > then.json
        python build_report.py then.json now.json > report.md
        echo report: $REPORT
        echo "::set-output name=comment::$REPORT"
    # make the comment
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        message: |
          Using ${{ github.sha }}:
          ${{ steps.report.outputs.comment }}
